In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset=pd.read_csv("CKD.csv")

In [3]:
dataset

,age,bp,sg,al,su,rbc,pc,pcc,ba,bgr,...,pcv,wc,rc,htn,dm,cad,appet,pe,ane,classification
0,2.000000,76.459948,c,3.0,0.0,normal,abnormal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,yes,no,yes
1,3.000000,76.459948,c,2.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,34.000000,12300.000000,4.705597,no,no,no,yes,poor,no,yes
2,4.000000,76.459948,a,1.0,0.0,normal,normal,notpresent,notpresent,99.000000,...,34.000000,8408.191126,4.705597,no,no,no,yes,poor,no,yes
3,5.000000,76.459948,d,1.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,38.868902,8408.191126,4.705597,no,no,no,yes,poor,yes,yes
4,5.000000,50.000000,c,0.0,0.0,normal,normal,notpresent,notpresent,148.112676,...,36.000000,12400.000000,4.705597,no,no,no,yes,poor,no,yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,219.000000,...,37.000000,9800.000000,4.400000,no,no,no,yes,poor,no,yes
395,51.492308,70.000000,c,0.0,2.0,normal,normal,notpresent,notpresent,220.000000,...,27.000000,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
396,51.492308,70.000000,c,3.0,0.0,normal,normal,notpresent,notpresent,110.000000,...,26.000000,9200.000000,3.400000,yes,yes,no,poor,poor,no,yes
397,51.492308,90.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,207.000000,...,38.868902,8408.191126,4.705597,yes,yes,no,yes,poor,yes,yes
398,51.492308,80.000000,a,0.0,0.0,normal,normal,notpresent,notpresent,100.000000,...,53.000000,8500.000000,4.900000,no,no,no,yes,poor,no,no

In [4]:
dataset=pd.get_dummies(dataset,drop_first=True)

In [5]:
dataset

,age,bp,al,su,bgr,bu,sc,sod,pot,hrmo,...,pc_normal,pcc_present,ba_present,htn_yes,dm_yes,cad_yes,appet_yes,pe_yes,ane_yes,classification_yes
0,2.000000,76.459948,3.0,0.0,148.112676,57.482105,3.077356,137.528754,4.627244,12.518156,...,0,0,0,0,0,0,1,1,0,1
1,3.000000,76.459948,2.0,0.0,148.112676,22.000000,0.700000,137.528754,4.627244,10.700000,...,1,0,0,0,0,0,1,0,0,1
2,4.000000,76.459948,1.0,0.0,99.000000,23.000000,0.600000,138.000000,4.400000,12.000000,...,1,0,0,0,0,0,1,0,0,1
3,5.000000,76.459948,1.0,0.0,148.112676,16.000000,0.700000,138.000000,3.200000,8.100000,...,1,0,0,0,0,0,1,0,1,1
4,5.000000,50.000000,0.0,0.0,148.112676,25.000000,0.600000,137.528754,4.627244,11.800000,...,1,0,0,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
394,51.492308,70.000000,0.0,0.0,219.000000,36.000000,1.300000,139.000000,3.700000,12.500000,...,1,0,0,0,0,0,1,0,0,1
395,51.492308,70.000000,0.0,2.0,220.000000,68.000000,2.800000,137.528754,4.627244,8.700000,...,1,0,0,1,1,0,1,0,1,1
396,51.492308,70.000000,3.0,0.0,110.000000,115.000000,6.000000,134.000000,2.700000,9.100000,...,1,0,0,1,1,0,0,0,0,1
397,51.492308,90.000000,0.0,0.0,207.000000,80.000000,6.800000,142.000000,5.500000,8.500000,...,1,0,0,1,1,0,1,0,1,1
398,51.492308,80.000000,0.0,0.0,100.000000,49.000000,1.000000,140.000000,5.000000,16.300000,...,1,0,0,0,0,0,1,0,0,0

In [6]:
dataset.columns

Index(['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv',
       'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal',
       'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes',
       'appet_yes', 'pe_yes', 'ane_yes', 'classification_yes'],
      dtype='object')

In [7]:
dataset["classification_yes"].value_counts()

1    249
0    150
Name: classification_yes, dtype: int64

In [8]:
indep=dataset[['age', 'bp', 'al', 'su', 'bgr', 'bu', 'sc', 'sod', 'pot', 'hrmo', 'pcv', 'wc', 'rc', 'sg_b', 'sg_c', 'sg_d', 'sg_e', 'rbc_normal', 'pc_normal', 'pcc_present', 'ba_present', 'htn_yes', 'dm_yes', 'cad_yes', 'appet_yes', 'pe_yes', 'ane_yes']]
dep=dataset["classification_yes"]

In [9]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(indep, dep, test_size = 1/3, random_state = 0)

In [10]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform(x_train)
x_test = sc.transform(x_test)

In [11]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import GridSearchCV
param_grid = {'criterion':['gini', 'entropy', 'log_loss'],
             'max_features':['auto','sqrt','log2'],
             'splitter':['best','random']}
grid = GridSearchCV(DecisionTreeClassifier(),param_grid,refit=True,verbose=3,n_jobs=-1,scoring='f1_weighted')
grid.fit(x_train,y_train)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

C:\Users\Genuine\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:372: FitFailedWarning:
30 fits failed out of a total of 90.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
30 fits failed with the following error:
Traceback (most recent call last):
  File "C:\Users\Genuine\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py", line 681, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "C:\Users\Genuine\Anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 942, in fit
    X_idx_sorted=X_idx_sorted,
  File "C:\Users\Genuine\Anaconda3\lib\site-packages\sklearn\tree\_classes.py", line 352, in fit
    criterion = CRITERIA_CLF[self.criterion](
KeyError: 'log_loss'

  warnings.warn(some_fits_failed_message, FitFailedWarning)
C:\Users\Genuine\Anaconda3\lib\site-packages\sklearn\model_selection\_search.py:972: UserWarning: One or more of the test scores are non-finite: [0.96205604 0.9438987  0.94393625 0.95484273 0.94733651 0.94031841
 0.91282147 0.9515817  0.93554085 0.95535115 0.93642362 0.94435206
        nan        nan        nan        nan        nan        nan]
  category=UserWarning,

GridSearchCV(estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_features': ['auto', 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             scoring='f1_weighted', verbose=3)

In [12]:
re=grid.cv_results_
grid_predictions = grid.predict(x_test) 
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, grid_predictions)   
from sklearn.metrics import classification_report
clf_report = classification_report(y_test, grid_predictions)

In [13]:
 from sklearn.metrics import f1_score
f1_macro = f1_score(y_test, grid_predictions, average = 'weighted')
print('The f1_macro value for best parameter {}'.format(grid.best_params_),f1_macro)

The f1_macro value for best parameter {'criterion': 'gini', 'max_features': 'auto', 'splitter': 'best'} 0.9402326571144843

In [14]:
print('The Confusion Matrix:\n',cm)

The Confusion Matrix:
 [[49  2]
 [ 6 76]]

In [15]:
print('The Report:\n',clf_report)

The Report:
               precision    recall  f1-score   support

           0       0.89      0.96      0.92        51
           1       0.97      0.93      0.95        82

    accuracy                           0.94       133
   macro avg       0.93      0.94      0.94       133
weighted avg       0.94      0.94      0.94       133

In [16]:
from sklearn.metrics import roc_auc_score
roc_auc_score(y_test,grid.predict_proba(x_test)[:,1])

0.9438067910090866

In [17]:
table = pd.DataFrame.from_dict(re)

In [18]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.006407,3.203620e-03,0.009597,0.011759,gini,auto,best,"{'criterion': 'gini', 'max_features': 'auto', ...",1.000000,0.962264,0.925524,0.922492,1.000000,0.962056,0.033998,1
1,0.003201,3.919834e-03,0.004802,0.003921,gini,auto,random,"{'criterion': 'gini', 'max_features': 'auto', ...",0.981569,0.944161,0.888286,0.943651,0.961826,0.943899,0.031091,8
2,0.006401,5.987378e-03,0.006401,0.005988,gini,sqrt,best,"{'criterion': 'gini', 'max_features': 'sqrt', ...",0.945100,0.924528,0.925524,0.962264,0.962264,0.943936,0.016666,7
3,0.001602,3.203106e-03,0.009599,0.005987,gini,sqrt,random,"{'criterion': 'gini', 'max_features': 'sqrt', ...",1.000000,0.925272,0.944023,0.961826,0.943093,0.954843,0.025367,3
4,0.003201,3.920184e-03,0.011201,0.008160,gini,log2,best,"{'criterion': 'gini', 'max_features': 'log2', ...",0.945100,0.962264,0.962573,0.943093,0.923652,0.947337,0.014415,5
5,0.004800,6.400073e-03,0.006401,0.005987,gini,log2,random,"{'criterion': 'gini', 'max_features': 'log2', ...",0.926567,0.943699,0.944023,0.943651,0.943651,0.940318,0.006877,9
6,0.003200,3.919600e-03,0.003202,0.003921,entropy,auto,best,"{'criterion': 'entropy', 'max_features': 'auto...",0.963284,0.943041,0.869849,0.922492,0.865441,0.912821,0.039102,12
7,0.003200,3.918842e-03,0.004781,0.003903,entropy,auto,random,"{'criterion': 'entropy', 'max_features': 'auto...",0.926978,0.961755,0.925524,0.943651,1.000000,0.951582,0.027550,4
8,0.008001,6.503192e-07,0.000000,0.000000,entropy,sqrt,best,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.944707,0.885265,0.944023,0.922492,0.981217,0.935541,0.031433,11
9,0.004800,3.919251e-03,0.001601,0.003201,entropy,sqrt,random,"{'criterion': 'entropy', 'max_features': 'sqrt...",0.908877,0.943041,0.962573,1.000000,0.962264,0.955351,0.029681,2
10,0.006400,3.200032e-03,0.001581,0.003161,entropy,log2,best,"{'criterion': 'entropy', 'max_features': 'log2...",0.926978,0.943699,0.925524,0.962264,0.923652,0.936424,0.014777,10
11,0.006401,3.200340e-03,0.000000,0.000000,entropy,log2,random,"{'criterion': 'entropy', 'max_features': 'log2...",0.890467,0.944161,0.981217,0.943651,0.962264,0.944352,0.030279,6
12,0.003201,3.920477e-03,0.000000,0.000000,log_loss,auto,best,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,13
13,0.001601,3.201199e-03,0.000000,0.000000,log_loss,auto,random,"{'criterion': 'log_loss', 'max_features': 'aut...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,14
14,0.003202,3.922053e-03,0.000000,0.000000,log_loss,sqrt,best,"{'criterion': 'log_loss', 'max_features': 'sqr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,15
15,0.003195,3.913248e-03,0.000000,0.000000,log_loss,sqrt,random,"{'criterion': 'log_loss', 'max_features': 'sqr...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,16
16,0.003202,3.921528e-03,0.000000,0.000000,log_loss,log2,best,"{'criterion': 'log_loss', 'max_features': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,17
17,0.001594,3.188705e-03,0.000000,0.000000,log_loss,log2,random,"{'criterion': 'log_loss', 'max_features': 'log...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,18